Repository etclabscore/expedition, pull requests merged in 2020-01, with the labels that each got.

#211 fix: bump multi-geth version
  src/stores/useMultiGethStore.ts
Labels: dependencies

#221 feat: address transactions + gas usage meters
  src/App.tsx
  src/components/AddressTransactions/AddressTransactions.tsx
  src/components/AddressTransactions/index.ts
  src/components/BlockList/BlockList.tsx
  src/components/BlockView/BlockView.tsx
  src/components/TxList/TxList.tsx
  src/containers/Address.tsx
  src/translations/cn.ts
  src/translations/en.ts
  src/translations/kr.ts
Labels: enhancement

#230 experimental: isaac's hacks
  package-lock.json
  src/components/BlockList/BlockList.tsx
  src/containers/Dashboard.tsx
Labels: enhancement, good first issue

#232 fix: add miner stats pagination by block range
  src/App.tsx
  src/components/BlockList/BlockList.tsx
  src/components/BlockPagination/BlockPagination.tsx
  src/components/BlockPagination/index.ts
  src/components/MinerStats.tsx
  src/components/StatCharts/StatCharts.tsx
  src/components/StatCharts/index.ts
  src/containers/Dashboard.tsx
  src/containers/MinerStatsPage.tsx
  src/translations/cn.ts
  src/translations/en.ts
  src/translations/kr.ts
Labels: enhancement
